const dataObj = {
  "login": "BrianReisman",
  "id": 70671932,
  "node_id": "MDQ6VXNlcjcwNjcxOTMy",
  "avatar_url": "https://avatars2.githubusercontent.com/u/70671932?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/BrianReisman",
  "html_url": "https://github.com/BrianReisman",
  "followers_url": "https://api.github.com/users/BrianReisman/followers",
  "following_url": "https://api.github.com/users/BrianReisman/following{/other_user}",
  "gists_url": "https://api.github.com/users/BrianReisman/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/BrianReisman/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/BrianReisman/subscriptions",
  "organizations_url": "https://api.github.com/users/BrianReisman/orgs",
  "repos_url": "https://api.github.com/users/BrianReisman/repos",
  "events_url": "https://api.github.com/users/BrianReisman/events{/privacy}",
  "received_events_url": "https://api.github.com/users/BrianReisman/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Brian Reisman",
  "company": null,
  "blog": "",
  "location": "remote",
  "email": null,
  "hireable": null,
  "bio": "Tech, travel, and theater. A terrific trio!",
  "twitter_username": null,
  "public_repos": 55,
  "public_gists": 0,
  "followers": 1,
  "following": 2,
  "created_at": "2020-09-03T00:14:16Z",
  "updated_at": "2020-12-11T03:06:36Z"
}
export default dataObj;